version: '2'

services:
  db:
    image: mdillon/postgis:9.5
    restart: always
    env_file: .env
    ports:
    - "5432:5432"

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - db:db
    volumes:
      - /usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 runserver:app

  nginx:
  #  restart: always
    build: ./nginx/
    ports:
      - "80:5000"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
