version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    external_links:
      - sotsdbcontainer_db_1:db
    networks:
      - default
    volumes:
      - /usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 runserver:app

  nginx:
  #  restart: always
    build: ./nginx/
    networks:
      - default
    ports:
      - "80:5000"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

networks:
  default:
    external:
      name: sotsdbcontainer_default